### PR TITLE
add materialize boilerplate

### PR DESCRIPTION
**Pull request by Kestanous**
As requested ^_^

### CODE REVIEW

**Comment by splendido** [comment]
Out of curiosity,  what's the stuff under the `.idea` folder?

**Comment by Kestanous** [comment]
No idea... That was in the semantic-ui folder that I `cp -r`ed. I figured it was something of yours and left it.

**Comment by splendido** [comment]
Oh, really?!
...so this migjt be something left around by @kevohagan?

I'll try to clean them a bit tomorrow. 

Btw, awesome contribution @Kestanous!

**Comment by kevohagan** [comment]
.idea is folder that webstorm creates and that contains info of the project
(project strutucre, workspace etc )

this is definitely somehting to clean up as its completely irrelevant to
useraccounts

that might be my errro! sorry guys ;)

On 3 February 2015 at 23:33, Luca Mussi <notifications@github.com> wrote:

> Merged #6 <https://github.com/meteor-useraccounts/boilerplates/pull/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor-useraccounts/boilerplates/pull/6#event-229634224>
> .
>



-- 
Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by splendido** [comment]
Ok, good to know!
...no worries, I'll clean them up!

Tnx!

**Pull request merged**
